import Head from "next/head";
import BarNav from "./BarNav";


export default function Home() {
  return (
    <>
    
      <Head>
        <title>Malo H</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/maloH.ico"/>
      </Head>
      <BarNav/>
      <div>
        <h1> Pagina Principal</h1>
        
      </div>
    </>
  );
}
